server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: study-room-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tomato_study_room?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1939366582
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tomato.studyroom.entity
  global-config:
    db-config:
      id-type: auto
      table-underline: true

logging:
  level:
    com.tomato.studyroom: debug
    org.springframework.web: info
